# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# now alias $(now) thing
version: 2
general:
  branches:
    only:
      - master # list of branches to build
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Install globals
      - run: sudo npm i -g now@canary --unsafe-perm

      # BACKEND STUFF
      - run: yarn install
        
      - run: now deploy --force --token=$NOW_TOKEN -e ENV=production -e MLAB_URL=$MLAB_URL &> /tmp/domain

      - run:
          name: Creating Alias For app-backend
          command: |
            echo "The freshly deployed instance has address:"
            NEW_URL=`cat /tmp/domain`
            echo $NEW_URL
            sleep 45
            set +e
            now alias --token=$NOW_TOKEN
            echo "y" | now rm api.erasmoose.com --safe --token=$NOW_TOKEN
     